Public Class TransTypes
    Property CCSale = "cc:sale"
    Property CCRefund = "cc:refund"
    Property CCAuth = "cc:authonly"
    Property Reset = "EMVPadReset"
    Property Sale = "EMVSale"
    Property SaleWithToken = "SaleByRecordNo"
    Property VoidSale = "EMVVoidSale"
    Property VoiddSaleByRecordNo = "VoidSaleByRecordNo"
    Property Auth = "EMVPreAuth"
    Property AuthByToken = "PreAuthByRecordNo"
    Property Refund = "EMVReturn"
    Property RefundWithToken = "ReturnByRecordNo"
    Property VoidRefund = "EMVVoidReturn"
    Property VoidRefundByRecordNo = "VoidReturnByRecordNo"
    Property VoiceAuth = "EMVVoiceAuth"
    Property ZeroAuth = "EMVZeroAuth"
    Property Adjust = "cc:adjust"
    Property AuthCapture = "PreAuthCaptureByRecordNo"
    Property GetSignature = "GetSignature"
    Property ParamDownload = "EMVParamDownload"
    Property GetVersion = "ServerVersion"
    Property GetBatchTotals = "BatchSummary"
    Property CloseBatch = "BatchClose"
    Property UploadOffline = "SAF_ForwardAll"

End Class